### ISSUE TITLE
RuntimeError: DataLoader worker (pid 22114) is killed by signal: Killed. 

### ISSUE THREAD

**Issue by JXZe** [batra-mlp-lab/visdial-challenge-starter-pytorch#10]
If I set the cpu-workers to be 4 , then after hundreds of iterations, I got error “RuntimeError: DataLoader worker (pid 22114) is killed by signal: Killed.”

I searched related topics, some suggested “cpu-workers=0”. So I set it to be 0 but after hundreds of iterations, I still got killed. This time, only “Killed” is given. No other hints.

In the meantime, when I set ''cpu-workers=0'', training is too slow ，about 1.1～2 s/it.

In the end, I want to know how long it took you to train this model.

**Comment by abhshkdz** [comment]
Hey @JXZe, the worker getting killed seems like a memory issue..

Are you getting 1.1 - 2s/iteration on 4 GPUs with batch size = 128? That doesn't sound too bad then. 

We were getting close to ~3 seconds per iteration on 4 GPUs (batch size 128) and ~1 second per iteration on 1 GPU (batch size 32), both with 4 workers. And it takes about an hour / epoch; and 10 hours overall to get to the best checkpoint.

**Comment by JXZe** [comment]
Thank you！

I successfully trained the model by adding memory.

And I were getting 3~4 seconds per iteration on 4 GPU (batch size 128) with 4 wokers. And it takes about 1.5 hours / epoch.
