### ISSUE TITLE
visdial_1.0_val_dense_annotations.json

### ISSUE THREAD

**Issue by angelboy000** [batra-mlp-lab/visdial-challenge-starter-pytorch#11]
Hi, where is the file of “visdial_1.0_val_dense_annotations.json”？

**Comment by abhshkdz** [comment]
[dropbox.com/s/3knyk09ko4xekmc/visdial_1.0_val_dense_annotations.json](https://www.dropbox.com/s/3knyk09ko4xekmc/visdial_1.0_val_dense_annotations.json?dl=1)

(also linked from https://visualdialog.org/data)
