### ISSUE TITLE
extract image features

### ISSUE THREAD

**Issue by wh0330** [batra-mlp-lab/visdial-challenge-starter-pytorch#12]
Hi, thanks for sharing the visual dialog challenge code. If i extract image features by mtself, where can i get "config_faster_rcnn_x101.yaml" and "model_faster_rcnn_x101.pkl"?

**Comment by kdexd** [comment]
Hi @wh0330, you could download any of the Faster RCNN models with pre-computed object proposals from the Detectron Model Zoo:

https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md

Also, you can find corresponding config files (named appropriately) here:

https://github.com/facebookresearch/Detectron/tree/master/configs/12_2017_baselines

**Comment by wh0330** [comment]
Thank you for replying.
