### ISSUE TITLE
Tokenizing is slow

### ISSUE THREAD

**Issue by idansc** [batra-mlp-lab/visdial-challenge-starter-pytorch#13]
The tokenization process is too slow, specifically for debug needs. A debug option, or option to load pre-processed file will be appreciated.

**Comment by shubhamagarwal92** [comment]
@abhshkdz As the design strategy is hugely inspired from Allennlp, I think it would be better to allow `lazy` data loading. (?) Or providing a sample of 5 dataset points to debug.

**Comment by kdexd** [comment]
That makes sense. Feel free to open a PR, or I can take this up by late June.

**Comment by shubhamagarwal92** [comment]
@idansc @kdexd I got some time to write a script to extract a subset of data. See the commit https://github.com/shubhamagarwal92/visdial-challenge-starter-pytorch/commit/9b2f0d3629e154eab5e0746d066cfc042d6fe73d

As the individual questions & answers in the dialogs reference the index from the list of all questions and answers, unfortunately, we would have to maintain the list of all possible questions and answers. 

One other possible remedy for this is to map the index again to the subset questions (and answers) or create a dummy dataset altogether.

**Comment by shubhamagarwal92** [comment]
@kdexd @abhshkdz Was there any specific reason not to create any pre-processed version (tensor format) of the data? Since currently data loading is too slow!

**Comment by kdexd** [comment]
@shubhamagarwal92 It was largely a personal preference; once the debugging is done, it took barely a few minutes to preprocess everything followed by (relatively longer) hours of training until convergence. In that spirit, I preferred keeping the preprocessing / repo setup minimal and shifting everything to be done on the fly.

Preference (and patience) is subjective, and we get this perspective from our user base. This feedback helps in iterative development and balancing both sides - for example, your PR! :)

**Comment by shubhamagarwal92** [comment]
@kdexd Thanks for your response. I see what you mean and I agree that the recent trend is to do everything on the fly (also in allennlp a bit)! But, I believe we can do that for small datasets but visdial is large enough that it hampers the speed (?) Related to #17 If I calculate the embeddings on the fly it is too slow, and if I pre-compute this, I have to change a lot of code in dataset readers. 

Anyways, thanks for the PR! 

Solved by #20

**Comment by kdexd** [comment]
Awesome! Let's shift to #17 for discussion.

**Comment by kdexd** [comment]
@idansc: closing this issue. For now, #20 seems to make tokenization significantly faster. Feel free to re-open if you have questions/concerns/suggestions, thanks!
