### ISSUE TITLE
Dense annotations of part of training split

### ISSUE THREAD

**Issue by quanguet** [batra-mlp-lab/visdial-challenge-starter-pytorch#19]
I've read the analysis from 2019 challenge winners. They mentioned that there is part of training split which has the dense annotations. Could you kindly update where we can download this file?
Thanks a lot.

**Comment by abhshkdz** [comment]
Mentioned [here](https://visualdialog.org/challenge/2019#evaluation).

Dense annotations on all of v1.0 val: https://www.dropbox.com/s/3knyk09ko4xekmc/visdial_1.0_val_dense_annotations.json, and dense annotations on 2000 images from v1.0 train: https://www.dropbox.com/s/1ajjfpepzyt3q4m/visdial_1.0_train_dense_sample.json.
