### ISSUE TITLE
ffi.lua:56 expected align(#) on line 579 

### ISSUE THREAD

**Issue by bedsDev** [batra-mlp-lab/visdial-challenge-starter-pytorch#2]
When run command
`th prepro_img_vgg16.lua -imageRoot ../image_root -gpuid 0`

there are errors: 

`/home/denniswu/torch/install/bin/lua: .../denniswu/torch/install/share/lua/5.1/trepl/init.lua:389: .../denniswu/torch/install/share/lua/5.1/trepl/init.lua:389: ...me/denniswu/torch/install/share/lua/5.1/hdf5/ffi.lua:56: expected align(#) on line 579
stack traceback:
	[C]: in function 'error'
	.../denniswu/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	prepro_img_vgg16.lua:3: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
`

has anyone met this problem?

thanks in advance.

**Comment by kdexd** [comment]
@bedsDev what is the active gcc version on your machine? And did you specifically change it before or during installation of `torch-hdf5`?

**Comment by bedsDev** [comment]
@abhshkdz thank you for the reply. I just tried to run the demo and get the first feeling. Is it possible to give a separate instruction for the demo setup only? or indicate me which sections should be skipped.

I was doing text mining and very interested your VisDial.

Appreciate your help.

**Comment by bedsDev** [comment]
@kdexd thanks for the reply. I am using
`$ gcc --version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by bedsDev** [comment]
I just hope I can run the visualisation and query locally by your offered data, then I can move on back to do other parts. I will check the two references gits to find whether I am luck to run a demo. Thanks a lot

**Comment by abhshkdz** [comment]
torch-hdf5 with lua 5.1 and gcc 4.8 / 4.9 (instead of gcc 5.4) should work. Could you give that a shot?

**Comment by spx1997** [comment]
torch-hdf5 with lua 5.2 and gcc 4.8 can work. I think it has a relationship with version of gcc
