### ISSUE TITLE
Late Fusion demo not working

### ISSUE THREAD

**Issue by shubhamagarwal92** [batra-mlp-lab/visdial-challenge-starter-pytorch#29]
Hi @abhshkdz @kdexd,

Could you please check the url for the "Late Fusion (2019)" demo on "Visual Chatbot". 

It currently redirects to http://demo-visualdialog.cloudcv.org/

**Comment by abhshkdz** [comment]
Ah, thanks for letting us know! Seems like it's been down for a couple of days. Looking into it.

**Comment by abhshkdz** [comment]
This is fixed now. http://demo.visualdialog.org/
