### ISSUE TITLE
About concat_history in dataset.py

### ISSUE THREAD

**Issue by gicheonkang** [batra-mlp-lab/visdial-challenge-starter-pytorch#32]
Hi, concat_history flag in dataset.py is quite confusing. 

I think `if self.config.get("concat_history", True):` would be correct 
not `if self.config.get("concat_history", False):`.

Due to the code above, the dataloader returns the concatenated history if concat_history==False.

**Comment by kdexd** [comment]
Hi! I am not quite sure if I understand, `.get` method of builtin dict allows option to specify a "default" value if the key does not exist. Here `if self.config.get("concat_history", False):` would simply default to NOT concatenating history if `concat_history` does not exist in config dict. You can specify `concat_history` as False and it will still skip concatenating history.

For example, try out this snippet:

```python
>>> letters = {"a": 1, "b": 2}
>>> letters["c"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'c'
>>> letters.get("c", 3)
3
>>> letters["c"] = 4
>>> letters.get("c", 3)
4
```

Does this make sense? Let me know if you have further concerns.

**Comment by gicheonkang** [comment]
Thank you so much. I'm deluding myself :)

**Comment by kdexd** [comment]
Glad it helped!
