### ISSUE TITLE
generative decoder

### ISSUE THREAD

**Issue by angelboy000** [batra-mlp-lab/visdial-challenge-starter-pytorch#4]
Hi, Can you share the generative decoder model in baseline?

**Comment by kdexd** [comment]
Hi @angelboy000:

I was thinking of adding it in during the recent refactor. It should be ready by late January 2019. Cheers!

**Comment by abhshkdz** [comment]
@angelboy000 this was added in https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch/commit/268f74fb49aada60da8c69a9e86b60bd65f7823d.

**Comment by shubhamagarwal92** [comment]
@kdexd @abhshkdz I guess we have the greedy decoder in this commit. Any plans of adding beam search decoder anytime soon?
