### ISSUE TITLE
missing file 'data/visdial_1.0_train.json' when running train.py

### ISSUE THREAD

**Issue by djbeymer** [batra-mlp-lab/visdial-challenge-starter-pytorch#9]
Thanks for posting the visual dialog challenge code.  When going through the readme file, I could follow it up to the step where wee invoke training.  When running 
      python train.py --config-yml configs/lf_disc_faster_rcnn_x101.yml --gpu-ids 4 5 6 7
I get the following error.  I cannot seem to find 'data/visdial_1.0_train.json'

(visdialch) beymer@alm00:~/VisualDialog/visdial-challenge-starter-pytorch$ python train.py --config-yml configs/lf_disc_faster_rcnn_x101.yml --gpu-ids 4 5 6 7
dataset:
  concat_history: true
  image_features_test_h5: data/features_faster_rcnn_x101_test.h5
  image_features_train_h5: data/features_faster_rcnn_x101_train.h5
  image_features_val_h5: data/features_faster_rcnn_x101_val.h5
  img_norm: 1
  max_sequence_length: 20
  vocab_min_count: 5
  word_counts_json: data/visdial_1.0_word_counts_train.json
model:
  decoder: disc
  dropout: 0.5
  encoder: lf
  img_feature_size: 2048
  lstm_hidden_size: 512
  lstm_num_layers: 2
  word_embedding_size: 300
solver:
  batch_size: 128
  initial_lr: 0.01
  lr_gamma: 0.1
  lr_milestones:
  - 4
  - 7
  - 10
  num_epochs: 20
  training_splits: train
  warmup_epochs: 1
  warmup_factor: 0.2

config_yml          : configs/lf_disc_faster_rcnn_x101.yml
train_json          : data/visdial_1.0_train.json
val_json            : data/visdial_1.0_val.json
val_dense_json      : data/visdial_1.0_val_dense_annotations.json
gpu_ids             : [4, 5, 6, 7]
cpu_workers         : 4
overfit             : False
validate            : False
in_memory           : False
save_dirpath        : checkpoints/
load_pthpath        : 
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    config["dataset"], args.train_json, overfit=args.overfit, in_memory=args.in_memory
  File "/home/beymer/VisualDialog/visdial-challenge-starter-pytorch/visdialch/data/dataset.py", line 26, in __init__
    self.dialogs_reader = DialogsReader(dialogs_jsonpath)
  File "/home/beymer/VisualDialog/visdial-challenge-starter-pytorch/visdialch/data/readers.py", line 35, in __init__
    with open(dialogs_jsonpath, "r") as visdial_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/visdial_1.0_train.json'

**Comment by abhshkdz** [comment]
You can download it from here: https://visualdialog.org/data.

We'll add it to the readme, sorry about that.

**Comment by kdexd** [comment]
Done!

**Comment by djbeymer** [comment]
Thanks, with these additional files I am able to kick off training.
